[package]
name = "sniffnet"
version = "0.1.0"
edition = "2021"
description = "Application to sniff and filter network traffic. Generates a human-readable report of the observed packets."
repository = "https://github.com/Crirock/pdsproject"
readme = "README.md"
keywords = ["cli", "network", "sniffer", "packet", "parser"]
categories = ["command-line-utilities", "concurrency", "network-programming"]
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.2"
etherparse = "0.12.0"
clap = { version = "3.2.6", features = ["derive"] }
chrono = "0.4.20"
crossterm = "0.13.3"
colored = "2.0.0"