[package]
name = "sniffnet"
version = "0.3.2"
edition = "2021"
description = "Application to sniff and filter network traffic. Generates a human-readable report of the observed packets."
repository = "https://github.com/Crirock/pdsproject"
readme = "README.md"
keywords = ["filter", "network", "packet", "sniffer", "parser"]
categories = ["command-line-utilities", "concurrency", "network-programming"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.10.1"
etherparse = "0.12.0"
clap = { version = "3.2.6", features = ["derive"] }
chrono = "0.4.20"
crossterm = "0.13.3"
colored = "2.0.0"
thousands = "0.2.0"
#charts = "0.3.0"


#used for debug purposes to measure time needed to write output file report
#[features]
#default = ["elapsed_time"]
#elapsed_time = []

#experimental: plot received packets in a line series chart
#[features]
#default = ["draw_graph"]
#draw_graph = []