[package]
name = "sniffnet"
version = "1.0.1"
authors = ["Giuliano Bellini"]
edition = "2021"
description = "Application to comfortably monitor your network traffic"
readme = "README.md"
repository = "https://github.com/GyulyVGC/sniffnet"
license = "MIT OR Apache-2.0"
keywords = ["filter", "network", "packet", "sniffer", "parser"]
categories = ["command-line-utilities", "concurrency", "network-programming"]
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]


[package.metadata.bundle]
name = "Sniffnet"
identifier = "gyulyvgc.sniffnet"
icon = ["./resources/logos/icon.ico"]


[profile.release]
opt-level = 3
lto = true


[dependencies]
pcap = "1.0.0"
etherparse = "0.13.0"
chrono = { version = "0.4.22", default_features = false, features = ["clock"] }
thousands = "0.2.0"
indexmap = "1.9.1"
plotters = { version = "0.3.4", default_features = false, features = ["area_series"] }
iced = { version = "0.6.0", features = ["tokio", "image"] }
plotters-iced = "0.5.0"
iced_style = "0.5.1"
db_ip = { version = "0.3.7", default_features = false, features = ["ipv4", "ipv6","include-country-code-lite"] }
confy = "0.5.1"
serde = { version = "1.0.149", default_features = false, features = ["derive"] }
rodio = { version = "0.16.0", default_features = false, features = ["mp3"] }
