[package]
name = "sniffnet"
version = "0.5.0"
edition = "2021"
authors = ["me"]
description = "Framework to explore network traffic through graphical and textual reports"
repository = "https://github.com/GyulyVGC/sniffnet"
readme = "README.md"
keywords = ["filter", "network", "packet", "sniffer", "parser"]
categories = ["command-line-utilities", "concurrency", "network-programming"]
license = "MIT OR Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[package.metadata.bundle]
name = "Sniffnet"
identifier = "gyulyvgc.sniffnet"
icon = ["./resources/icon.ico"]


[dependencies]
pcap = "0.10.1"
etherparse = "0.12.0"
chrono = "0.4.20"
thousands = "0.2.0"
plotters = "0.3.4"
indexmap = "1.9.1"
plotters-iced = "0.3.3"
iced = {version = "0.4.2", features = ["smol", "canvas", "tokio"] }
iced_style = "0.4.0"
iced_native = "0.5.1"


#used for debug purposes to measure time needed to write output reports
#[features]
#default = ["elapsed_time"]
#elapsed_time = []