name = "Catppuccin (Mocha)"
description = "Catppuccin is a colorful, medium contrast pastel theme.\nhttps://github.com/catppuccin/catppuccin"

primary = "#1e1e2e"          # Base
secondary = "#89b4fa"        # Blue
buttons = "#89dceb"          # Sky
incoming = "#89b4fa"         # Blue
outgoing = "#f5c2e7"         # Pink
text_headers = "#cdd6f4"     # Text
text_body = "#cdd6f4"        # Text
round_borders = "#74c7ec"    # Sapphire
round_containers = "#585b70" # Surface 2
starred = "#f9e2af"          # Yellow
badge_alpha = 0.75
