# Colors are in RGB/RGBA hexadecimal.
primary = "#1e1e2e"           # Background
secondary = "#89b4fa"         # Headers / incoming connections
buttons = "#313244"           # Buttons
outgoing = "#f5c2e7"          # Outgoing connections
text_headers = "#11111b"      # Text headers
text_body = "#cdd6f4"         # Text body
starred = "#f9e2afaa"         # Favorites

# The following parameters are in the range [0.0, 1.0].
round_borders_alpha = 0.3     # Borders opacity
round_containers_alpha = 0.15 # Containers opacity
chart_badge_alpha = 0.2       # Chart opacity

# Set to true if the theme is dark, false if it's light.
nightly = true