# https://github.com/catppuccin/catppuccin
primary = "#24273a"           # Base
secondary = "#f5bde6"         # Pink
buttons = "#363a4f"           # Surface0
outgoing = "#c6a0f6"          # Mauve
text_headers = "#181926"      # Crust
text_body = "#cad3f5"         # Text
starred = "#eed49f"           # Yellow
round_borders_alpha = 0.1
round_containers_alpha = 0.15
chart_badge_alpha = 0.75
nightly = true
