# https://github.com/catppuccin/catppuccin"
primary = "#eff1f5"           # Base
secondary = "#1e66f5"         # Blue
buttons = "#ccd0da"           # Surface0
outgoing = "#ea76cb"          # Pink
text_headers = "#dce0e8"      # Crust
text_body = "#4c4f69"         # Text
starred = "#df8e1d"           # Yellow
round_borders_alpha = 0.15
round_containers_alpha = 0.25
chart_badge_alpha = 0.75
nightly = false
