# https://github.com/catppuccin/catppuccin
primary = "#303446"           # Base
secondary = "#a6d189"         # Green
buttons = "#414559"           # Surface0
outgoing = "#f4b8e4"          # Pink
text_headers = "#232634"      # Crust
text_body = "#c6d0f5"         # Text
starred = "#e5c890"           # Yellow
round_borders_alpha = 0.1
round_containers_alpha = 0.04
chart_badge_alpha = 0.55
nightly = true
