# https://github.com/catppuccin/catppuccin
primary = "#1e1e2e"           # Base
secondary = "#89b4fa"         # Blue
buttons = "#313244"           # Surface0
outgoing = "#f5c2e7"          # Pink
text_headers = "#11111b"      # Crust
text_body = "#cdd6f4"         # Text
starred = "#f9e2af"           # Yellow
round_borders_alpha = 0.1
round_containers_alpha = 0.15
chart_badge_alpha = 0.75
nightly = true
