# Colors are in RGB/RGBA hexadecimal.
primary = "#303446"           # Background
secondary = "#a6d189"         # Headers / incoming connections
outgoing = "#f4b8e4"          # Outgoing connections
text_headers = "#232634"      # Text headers
text_body = "#c6d0f5"         # Text body
starred = "#e5c890aa"         # Favorites