[palette]
primary = "#44475a"           # Current line
secondary = "#ff79c6"         # Pink
buttons = "#6272a4"           # Comment
outgoing = "#8be9fd"          # Cyan
text_headers = "#282a36"      # Background
text_body = "#f8f8f2"         # Foreground
starred = "#f1fa8cb2"         # Yellow
round_borders_alpha = 0.1
round_containers_alpha = 0.04
chart_badge_alpha = 0.15
nightly = true
