name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    name: Mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build mac
      run: cargo build --verbose
    - name: Run tests mac
      run: cargo test --verbose

    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build linux
      run: cargo build --verbose
    - name: Run tests linux
      run: cargo test --verbose

    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build windows
      run: cargo build --verbose
    - name: Run tests windows
      run: cargo test --verbose
